---

# THE FOLLOWING 3 CONTROLS WILL FAIL UNLESS THEY ARE IN THE FOLLOWING ORDER FOR CLOUD BASED SYSTEMS
# CONTROL WN11-AC-000010, CONTROL WN11-AC-000005, CONTROL WN11-AC-000015
# Needs to go before WN11-AC-000005 since the Lockout Duration could be disabled if the Lockout Policy is set to 0 causing the task to fail.
- name: "MEDIUM | WN11-AC-000010 | PATCH | The number of allowed bad logon attempts must be configured to 3 or less."
  when: wn11_ac_000010
  tags:
    - WN11-AC-000010
    - CAT2
    - CCI-000044
    - SRG-OS-000021-GPOS-00005
    - SV-253298r958388_rule
    - V-253298
    - NIST800-53_AC-7_a
    - NIST800-53A_AC-7.1_ii
    - NIST800-53R4_AC-7_a
  block:
    - name: "MEDIUM | WN11-AC-000010 | PATCH | The number of allowed bad logon attempts must be configured to 3 or less. | Set Variable"
      when:
        - win11stig_bad_login_lockout_count <= 3
        - win11stig_bad_login_lockout_count > 0
      community.windows.win_security_policy:
        section: System Access
        key: LockoutBadCount
        value: "{{ win11stig_bad_login_lockout_count }}"

    - name: "MEDIUM | WN11-AC-000010 | AUDIT | The number of allowed bad logon attempts must be configured to 3 or less. | Verify Variable Not 0 or more then 3 warning."
      when: win11stig_bad_login_lockout_count > 3 or win11stig_bad_login_lockout_count == 0
      ansible.builtin.debug:
        msg:
          - "Warning!! You have an invalid number of attempts set for win11stig_bad_login_lockout_count. Please read"
          - "the notes for the variable and make the necessary change to the variable to be in compliance."

    - name: "MEDIUM | WN11-AC-000010 | AUDIT | The number of allowed bad logon attempts must be configured to 3 or less. | Set warning count."
      when: win11stig_bad_login_lockout_count > 3 or win11stig_bad_login_lockout_count == 0
      ansible.builtin.import_tasks:
        file: warning_facts.yml
      vars:
        warn_control_id: 'WN11-AC-000010'

- name: "MEDIUM | WN11-AC-000005 | PATCH | Windows 11 account lockout duration must be configured to 15 minutes or greater."
  when: wn11_ac_000005
  tags:
    - WN11-AC-000005
    - CAT2
    - CCI-002238
    - SRG-OS-000329-GPOS-00128
    - SV-253297r958736_rule
    - V-253297
    - NIST800-53_AC-7_b
  block:
    - name: "MEDIUM | WN11-AC-000005 | PATCH | Windows 11 account lockout duration must be configured to 15 minutes or greater."
      when: win11stig_account_lockout_duration >= 15 or win11stig_account_lockout_duration == 0
      community.windows.win_security_policy:
        section: System Access
        key: LockoutDuration
        value: "{{ win11stig_account_lockout_duration }}"

    - name: "MEDIUM | WN11-AC-000005 | AUDIT | Windows 11 account lockout duration must be configured to 15 minutes or greater. | Verify variable set to 15 or more minutes warning."
      when: win11stig_account_lockout_duration < 15 and win11stig_account_lockout_duration != 0
      ansible.builtin.debug:
        msg:
          - "Warning!! You have an invalid number of minutes set for win11stig_account_lockout_duration please read"
          - "the notes for the variable and make the necessary change to the variable to be in compliance."

    - name: "MEDIUM | WN11-AC-000005 | AUDIT | Windows 11 account lockout duration must be configured to 15 minutes or greater. | Set warning count."
      when: win11stig_account_lockout_duration < 15 and win11stig_account_lockout_duration != 0
      ansible.builtin.import_tasks:
        file: warning_facts.yml
      vars:
        warn_control_id: 'WN11-AC-000005'

- name: "MEDIUM | WN11-AC-000015 | PATCH | The period of time before the bad logon counter is reset must be configured to 15 minutes."
  when: wn11_ac_000015
  tags:
    - WN11-AC-000015
    - CAT2
    - CCI-000044
    - SRG-OS-000021-GPOS-00005
    - SV-253299r958388_rule
    - V-253299
    - NIST800-53_AC-7_a
    - NIST800-53A_AC-7.1_ii
    - NIST800-53R4_AC-7_a
  # The Lockout Duration must be greater or equal to the Reset Account Lockout counter.
  block:
    - name: "MEDIUM | WN11-AC-000015 | PATCH | The period of time before the bad logon counter is reset must be configured to 15 minutes."
      when:
        - win11stig_account_lockout_counter_reset >= 15
        - win11stig_account_lockout_counter_reset <= win11stig_account_lockout_duration
      community.windows.win_security_policy:
        section: System Access
        key: ResetLockoutCount
        value: "{{ win11stig_account_lockout_counter_reset }}"

    - name: "MEDIUM | WN11-AC-000015 | AUDIT | The period of time before the bad logon counter is reset must be configured to 15 minutes. | Verify variable set to 15 or more minutes warning."
      when: win11stig_account_lockout_counter_reset > win11stig_account_lockout_duration or win11stig_account_lockout_counter_reset < 15
      ansible.builtin.debug:
        msg:
          - "Warning!! You have an invalid number of minutes set for win11stig_account_lockout_counter_reset. Please read"
          - "the notes for the variable and make the necessary change to the variable to be in compliance."

    - name: "MEDIUM | WN11-AC-000015 | AUDIT | The period of time before the bad logon counter is reset must be configured to 15 minutes. | Set warning count."
      when: win11stig_account_lockout_counter_reset > win11stig_account_lockout_duration or win11stig_account_lockout_counter_reset < 15
      ansible.builtin.import_tasks:
        file: warning_facts.yml
      vars:
        warn_control_id: 'WN11-AC-000015'
